api_register_user:
  path: /user/register
  controller: App\Controller\UserController::registerUser
  methods: POST

api_login_user:
  path: /user/login
  controller: App\Controller\UserController::loginUser
  methods: POST

api_get_user:
  path: /user/getUser
  controller: App\Controller\UserController::getUserByName
  methods: POST

api_user_password_reset:
  path: /user/passwordreset
  controller: App\Controller\UserController::resetPassword
  methods: POST

api_change_password:
  path: /user/changepassword
  controller: App\Controller\UserController::changePassword
  methods: PUT

api_update_user:
  path: /user/update
  controller: App\Controller\UserController::updateUser
  methods: PUT

api_delete_user:
  path: /user/delete
  controller: App\Controller\UserController::deleteUser
  methods: POST

api_get_user_rank:
  path: /user/getrank
  controller: App\Controller\UserController::getRank
  methods: GET

api_get_user_top_list:
  path: /user/toplist
  controller: App\Controller\UserController::getTopList
  methods: GET

api_get_user_image:
  path: /user/getUserImage
  controller: App\Controller\UserController::getUserImage
  methods: GET

api_upload_user_image:
  path: /user/uploadimage
  controller: App\Controller\UserController::uploadImage
  methods: PUT

api_get_user_money:
  path: /user/getmoney
  controller: App\Controller\UserController::getMoney
  methods: GET

api_add_user_money:
  path: /user/addmoney
  controller: App\Controller\UserController::addMoney
  methods: PUT

api_get_user_is_admin:
  path: /user/isadmin
  controller: App\Controller\UserController::isUserAdmin
  methods: GET

api_get_all_user:
  path: /user/getalluser
  controller: App\Controller\UserController::getAllUsers
  methods: POST

api_reset_mail:
  path: /user/resetpassword
  controller: App\Controller\UserController::sendResetPasswordMail
  methods: POST

#  ------------------------------------------------------- API-GAME ------------------------------------------ #
api_create_new_game:
  path: /game/createnew
  controller: App\Controller\GameController::createNewGame
  methods: POST

api_get_game:
  path: /game/getgame
  controller: App\Controller\GameController::getGame
  methods: POST

api_user_is_ingame:
  path: /game/isingame
  controller: App\Controller\GameController::isIngame
  methods: GET

api_delete_game:
  path: /game/deletegame
  controller: App\Controller\GameController::deleteGame
  methods: POST

api_start_game_socket:
  path: /game/startsocket
  controller: App\Controller\GameController::runProcess
  methods: GET
