api_register_user:
  path: /user/register
  controller: App\Controller\UserController::registerUser
  methods: POST

api_login_user:
  path: /user/login
  controller: App\Controller\UserController::loginUser
  methods: POST

api_change_password:
  path: /user/changepassword
  controller: App\Controller\UserController::changePassword
  methods: PUT

api_update_user:
  path: /user/update
  controller: App\Controller\UserController::updateUser
  methods: PUT

api_delete_user:
  path: /user/delete
  controller: App\Controller\UserController::deleteUser
  methods: POST

api_get_user_rank:
  path: /user/getrank
  controller: App\Controller\UserController::getRank
  methods: GET

api_get_user_top_list:
  path: /user/toplist
  controller: App\Controller\UserController::getTopList
  methods: GET

api_get_user_image:
  path: /user/getUserImage
  controller: App\Controller\UserController::getUserImage
  methods: GET

api_upload_user_image:
  path: /user/uploadimage
  controller: App\Controller\UserController::uploadImage
  methods: PUT

api_get_user_money:
  path: /user/getmoney
  controller: App\Controller\UserController::getMoney
  methods: GET

api_add_user_money:
  path: /user/addmoney
  controller: App\Controller\UserController::addMoney
  methods: PUT

api_get_user_is_admin:
  path: /user/isadmin
  controller: App\Controller\UserController::isUserAdmin
  methods: GET

api_get_all_user:
  path: /user/getalluser
  controller: App\Controller\UserController::getAllUsers
  methods: POST

api_reset_mail:
  path: /user/resetpassword
  controller: App\Controller\UserController::sendResetPasswordMail
  methods: POST

api_is_user_in_queue:
  path: /user/isinqueue
  controller: App\Controller\UserController::userIsInQueue
  methods: GET

api_get_players_in_queue:
  path: /queue/totalamount
  controller: App\Controller\UserController::getAmountOfPlayersInQueue
  methods: GET

api_add_player_to_queue:
  path: /queue/addtoqueue
  controller: App\Controller\UserController::addPlayerToQueue
  methods: POST

api_remove_player_from_queue:
  path: /queue/removefromqueue
  controller: App\Controller\UserController::removePlayerFromQueue
  methods: POST

api_get_queued_players:
  path: /queue/getqueued
  controller: App\Controller\UserController::getQueuedPlayers
  methods: GET

#  ------------------------------------------------------- API-GAME ------------------------------------------ #
api_create_new_game:
  path: /game/createnew
  controller: App\Controller\GameController::createNewGame
  methods: POST

api_get_game:
  path: /game/getgame
  controller: App\Controller\GameController::getGame
  methods: POST

api_user_is_ingame:
  path: /game/isingame
  controller: App\Controller\GameController::isIngame
  methods: GET

api_get_full_game:
  path: /game/getfullgame
  controller: App\Controller\GameController::getFullGame
  methods: POST

api_delete_game:
  path: /game/deletegame
  controller: App\Controller\GameController::deleteGame
  methods: POST

api_update_game:
  path: /game/updategame
  controller: App\Controller\GameController::updateGame
  methods: PUT

api_update_question:
  path: /game/updatequestion
  controller: App\Controller\GameController::updateQuestion
  methods: PUT

api_get_all_games:
  path: /game/getrunning
  controller: App\Controller\GameController::getAllRunning
  methods: POST
