api_register_user:
  path: /user/register
  controller: App\Controller\UserController::registerUser
  methods: POST

api_login_user:
  path: /user/login
  controller: App\Controller\UserController::loginUser
  methods: POST

api_change_password:
  path: /user/changepassword
  controller: App\Controller\UserController::changePassword
  methods: PUT

api_get_user_image:
  path: /user/getUserImage
  controller: App\Controller\UserController::getUserImage
  methods: GET

api_upload_user_image:
  path: /user/uploadimage
  controller: App\Controller\UserController::uploadImage
  methods: PUT

api_get_user_money:
  path: /user/getmoney
  controller: App\Controller\UserController::getMoney
  methods: GET

api_reset_mail:
  path: /user/resetpassword
  controller: App\Controller\UserController::sendResetPasswordMail
  methods: POST